faforever:
  api:
    base-url: http://localhost:8010
    client-id: postman
    client-secret: postman
    access-token-uri: ${faforever.api.base-url}/oauth/token
    max-page-size: 10_000
  vault:
    base-url: http://content.faforever.com
    replayDownloadUrlFormat: ${faforever.vault.base-url}/faf/vault/replay_vault/replay.php?id=%s
logging:
  level:
    com.faforever.moderatorclient: DEBUG
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
