faforever:
  api:
    base-url: https://api.faforever.com
    client-id: 05209670-36c5-40ad-b581-e71b7b49bd1a
    client-secret: 370965a5-e7f2-4fe1-9225-e4517476b6a5
    access-token-uri: ${faforever.api.base-url}/oauth/token
    max-page-size: 10_000
  vault:
    base-url: http://content.faforever.com
    replayDownloadUrlFormat: ${faforever.vault.base-url}/faf/vault/replay_vault/replay.php?id=%s
logging:
  level:
    com.faforever.moderatorclient: DEBUG
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false