faforever:
  api:
    base-url: https://api.faforever.com
    client-id: 05209670-36c5-40ad-b581-e71b7b49bd1a
    client-secret: 370965a5-e7f2-4fe1-9225-e4517476b6a5
    access-token-uri: ${faforever.api.base-url}/oauth/token
    max-page-size: 10_000
    max-result-size: 1_000_000
  map-generator:
    repo-and-owner-name: FAForever/Neroxis-Map-Generator
    query-versions-url: https://api.github.com/repos/${faforever.map-generator.repo-and-owner-name}/releases
    min-supported-version: 1.4.3
  vault:
    base-url: https://content.faforever.com
    replay-download-url-format: http://replay.faforever.com/%s
  environments:
    "[faforever.com]":
      base-url: https://api.faforever.com
      client-id: faf-moderator-client
      replay-download-url-format: https://replay.faforever.com/%s
      oauth-base-url: https://hydra.faforever.com
      oauth-redirect-url: http://localhost
      oauth-scopes: upload_avatar administrative_actions read_sensible_userdata manage_vault
      user-base-url: https://user.faforever.com
    "[test.faforever.com]":
      base-url: https://api.test.faforever.com
      client-id: faf-moderator-client
      replay-download-url-format: https://replay.test.faforever.com/%s
      oauth-base-url: https://hydra.test.faforever.com
      oauth-redirect-url: http://localhost
      oauth-scopes: upload_avatar administrative_actions read_sensible_userdata manage_vault
      user-base-url: https://user.test.faforever.com
    "[localhost:8010]":
      base-url: http://localhost:8010
      client-id: faf-moderator-client
      replay-download-url-format: https://replay.test.faforever.com/%s
      oauth-base-url: http://localhost:4444
      oauth-redirect-url: http://localhost
      oauth-scopes: upload_avatar administrative_actions read_sensible_userdata manage_vault
      user-base-url: http://localhost:8080

logging:
  level:
    com.faforever.moderatorclient: DEBUG
spring:
  main:
    allow-circular-references: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
