faforever:
  api:
    base-url: http://localhost:8010
    client-id: postman-test
    client-secret: postman-test
    access-token-uri: ${faforever.api.base-url}/oauth/token
    max-page-size: 10_000
logging:
  level:
    com.faforever.moderatorclient: DEBUG